model:
  name: "resnet_custom"
  load_weights: "log/cosine/resnet_custom_motsynth_split3_train_mot17_test/model/resnetCustom_best.pth.tar-18"

data:
  type: "image"
  sources: ["motsynth_split3"]
  targets: ["mot17"]
  height: 256
  width: 128
  combineall: False
  transforms: ["random_flip"]
  save_dir: "log/cosine/resnet_custom_visrank"
  root: "c:/Users/Matteo/Desktop/cvcs/storage"
  workers: 0

test:
  batch_size: 64
  dist_metric: "cosine"
  normalize_feature: False
  evaluate: True
  eval_freq: 1
  rerank: False
  visrank: True
  visrank_topk: 10
  start_eval: 1
