model:
  name: "resnet18_fc512"
  load_weights: "log/cosine/resnet18_fc512_motsynth_split3_train_mot17_test/model/resnetFC_best.pth.tar-12"

data:
  type: "image"
  sources: ["motsynth_split3"]
  targets: ["mot17"]
  height: 256
  width: 128
  combineall: False
  transforms: ["random_flip"]
  save_dir: "log/cosine/resnet18_fc512_actmaps"
  root: "c:/Users/Matteo/Desktop/cvcs/storage"
  workers: 0
