model:
  name: "resnet18_fc512"
  pretrained: True

data:
  type: "image"
  sources: ["motsynth_split3"]
  targets: ["mot17"]
  height: 256
  width: 128
  combineall: False
  transforms: ["random_flip"]
  save_dir: "log/resnet18_fc512_motsynth_split3_train_mot17_test"
  root: "c:/Users/Matteo/Desktop/cvcs/storage"
  workers: 0

loss:
  name: "softmax"
  softmax:
    label_smooth: True

train:
  optim: "amsgrad"
  lr: 0.0009
  max_epoch: 20
  batch_size: 64
  fixbase_epoch: 3
  open_layers: ["fc", "classifier"]
  lr_scheduler: "single_step"
  stepsize: [9]

test:
  batch_size: 64
  dist_metric: "euclidean"
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False
  start_eval: 1
