model:
  name: "resnet18"
  load_weights: "log/euclidean/resnet18_motsynth_split3_train_mot17_test/model/resnet18_best.tar-9"

data:
  type: "image"
  sources: ["motsynth_split3"]
  targets: ["mot17"]
  height: 256
  width: 128
  combineall: False
  transforms: ["random_flip"]
  save_dir: "log/euclidean/resnet18_actmaps"
  root: "c:/Users/Matteo/Desktop/cvcs/storage"
  workers: 0
