model:
  name: "resnet_custom"
  load_weights: "log/euclidean/resnet_custom_motsynth_split3_train_mot17_test/model/resnetCustom_best.pth.tar-17"

data:
  type: "image"
  sources: ["motsynth_split3"]
  targets: ["mot17"]
  height: 256
  width: 128
  combineall: False
  transforms: ["random_flip"]
  save_dir: "log/euclidean/resnet_custom_actmaps"
  root: "c:/Users/Matteo/Desktop/cvcs/storage"
  workers: 0
